# Generated by Django 3.1.4 on 2021-02-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebanking', '0003_user_account_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='account_number',
            field=models.TextField(default='1234-5678'),
        ),
        migrations.AddField(
            model_name='user_account',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
